name: Schedule

"on":
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}      
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        # https://github.com/oven-sh/setup-bun/issues/37
        # with:
        #  bun-version: "1.x"
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - name: Run task
        run: bun start
      - name: Deply
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
